package io.openems.edge.kostal.plenticore.charger;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.kostal.plenticore.KostalPlenticoreConstants;

@ObjectClassDefinition(//
		name = "Kostal Plenticore DC Charger 2", //
		description = "Implements the Kostal DC Charger 2.")

@interface ConfigPV2 {
	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "charger1";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Kostal Plenticore ESS ", description = "ID of Kostal Plenticore Energy Storage System .")
	String ess_id() default "ess0";

	@AttributeDefinition(name = "Kostal Plenticore ESS target filter", description = "This is auto-generated by 'Kostal Plenticore ESS'.")
	String ess_target() default "(enabled=true)";

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default KostalPlenticoreConstants.DEFAULT_UNIT_ID;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Kostal Plenticore DC Charger 2 [{id}]";
}
